apiVersion: apps/v1
kind: Deployment
metadata:
  name: ontap-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ontap-api
  template:
    metadata:
      labels:
        app: ontap-api
    spec:
      containers:
      - name: ontap-api
        image: dharshu01/ontap-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: ontap-api-service
spec:
  selector:
    app: ontap-api
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: NodePort
